language: C++
os:
  - linux
  - osx

compiler:
  - g++
  - clang
 
script: make
  
addons:
  homebrew:
    packages:
      - beanstalk
  apt:
    packages:
      - libusb-1.0-0
      - libusb-1.0-0-dev
  
